FROM sgn0/couchbase-fast

EXPOSE 8091 8092 8093 8094 8095 8096 11207 11210 11211 18091 18092 18093 18094 18095 18096

ADD ./scripts/setup-data.sh /opt/couchbase/setup-data.sh
ADD ./scripts/scrub.sql /opt/couchbase/scrub.sql
RUN mkdir /backup
ADD data/backup.tgz /backup/

RUN mkdir /backup/data && mv /backup/bucket-jcl /backup/data && \
  /opt/couchbase/setup-data.sh && \
  rm /opt/couchbase/setup-data.sh && \
  rm -rf /backup

